server:
  port: 9001
spring:
  cloud:
    gateway:
      routes:
        - id: book
          uri: http://localhost:8001/
          predicates:
          - Path=/book/**
        - id: film
          uri: http://localhost:8002/
          predicates:
          - Path=/film/**  
